### ISSUE TITLE
After restart EH input stop work

### ISSUE THREAD

**Issue by bollicino** [logstash-plugins/logstash-input-azure_event_hubs#24]
**What happened:**

We're using the plugin on 2 Logstash instances, our pipeline config:
`input {
    azure_event_hubs {
        event_hub_connections => ["Endpoint=sb://elk-prod-westeurope-metricbeat.servicebus.windows.net/;SharedAccessKeyName=manage;SharedAccessKey=;EntityPath=k8s-metricbeat"]
        consumer_group => "logstash"
        decorate_events => true
        storage_connection => "DefaultEndpointsProtocol=https;AccountName=mystorage;AccountKey=;EndpointSuffix=core.windows.net"
        codec => "json"
        initial_position => "beginning"
    }
}
output {
  elasticsearch {
   index => "eventhub-%{+YYYY.MM.dd}"
   hosts => ["elk-prod-westeurope-elasticdata-2:9200","elk-prod-westeurope-elasticdata-1:9200","elk-prod-westeurope-elasticdata-0:9200"]
  }
}`

The configuration works fine, but after a restart Logstash is not able to connect again to the EH. And start to log this:
`[2018-12-10T15:22:56,281][INFO ][org.apache.qpid.proton.engine.BaseHandler] linkName[b22fbb_6ca_G19_1544455376014], ErrorCondition[amqp:internal-error, The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:be5d7da6-4a68-440f-a1ea-badca230d649, TrackingId:083b046d00011500000019695c0e84d0_G19_B13, SystemTracker:elk-prod-westeurope-metricbeat:eventhub:k8s-metricbeat~8191|logstash, Timestamp:2018-12-10T15:22:56]
`

Attached full startup log.

[logstash-eventhub.log](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/files/2664125/logstash-eventhub.log)

**What you expected to happen:**
Logstash works again after restart the service

**Environment:**

- Logstash version 6.5.2
- logstash-input-azure_event_hubs version 1.0.4
- OS Ubuntu 16.04.5 LTS
- Event Hubs Standard with Kafka Enable
- Azure Blob Storage

**Comment by robbavey** [comment]
@bollicino A new version of the plugin (`1.1.0`) was recently released - please try it and see if it fixes your issue.

**Comment by robbavey** [comment]
@bollicino As it has been several months since the reported fix, I am going to close this issue as fixed. If this is not the case, and the issue reoccurs with the latest version, please reopen this issue
