### ISSUE TITLE
Migrate issues from https://github.com/Azure/azure-diagnostics-tools/issues

### ISSUE THREAD

**Issue by jakelandis** [logstash-plugins/logstash-input-azure_event_hubs#5]
To complete the transfer of repositories, we need to evaluate the outstanding issues in https://github.com/Azure/azure-diagnostics-tools/issues and copy them over here if still applicable. 

This should be done after the conversion to Event Processor Host https://github.com/logstash-plugins/logstash-input-azure_event_hubs/pull/3 is completed.

**Comment by jakelandis** [comment]
@brahmnes - I have added comments to the relevant issues in https://github.com/Azure/azure-diagnostics-tools/issues , but lack the privilege to close the issue. If I missed any feel free to point them over here.

**Comment by brahmnes** [comment]
Hi @jakelandis,
I think I have them closed now.
