### ISSUE TITLE
decorate_events not working

### ISSUE THREAD

**Issue by Mugen1991** [logstash-plugins/logstash-input-azure_event_hubs#7]
I have decorate_events enabled (in an advanced config) and no fields are added.

```
input {
   azure_event_hubs {
     codec => "json"
     config_mode => "advanced"
     threads => 8
     decorate_events => true
     storage_connection => "DefaultEndpointsProtocol=...."
     event_hubs => [
        {"insights-operational-logs" => {
         event_hub_connection => "...."
        }},
      {"azurewebapp" => {
         event_hub_connection => "..."
       }}
     ]
   }
}

```

The document contains the following meta fields:

-   "_index"
-   "_type"
-   "_id"
-   "_version"
-   "_score"
-   "_source"

I am using logstash 6.2.4 and version 1.0.0 of logstash-input-azure_event_hubs.
Is there something wrong concerning my configuration  ?

**Comment by chriscoveyduck** [comment]
You need to map the metadata to fields as it's not sent to output by default.  See below.

filter {
  mutate {
    add_field => { "eventsource" => "%{[@metadata][azure_event_hubs][name]}" }
    add_field => { "logstash_instance" => "%{[@metadata][azure_event_hubs][processor_host]}" }
  }
}

You can also stream it via stdout if you want to get the field names to work with.

output {
   stdout { codec => rubydebug { metadata => true } }
}

**Comment by Mugen1991** [comment]
Works like a charm. You're awesome. Issue can be closed.
