### ISSUE TITLE
Upgrade com.microsoft.azure:azure-eventhubs to version 3.2.1 or higher

### ISSUE THREAD

**Issue by cspring86** [logstash-plugins/logstash-input-azure_event_hubs#95]
We're using a security tool called Snyk to scan our containers and it's reported a [Critical vulnerability](https://security.snyk.io/vuln/SNYK-JAVA-COMMICROSOFTAZURE-8230425) in "com.microsoft.azure:azure-eventhubs".

I can see from the `lib/logstash-input-azure_event_hubs.rb` file that this project is using version 2.3.2, which is vulnerable.

When will this project be looking to upgrade to version 3.2.1 or higher?

**Comment by robbavey** [comment]
A new version of the plugin has been released. 

Please update to version `1.5.0`
